; /etc/php/8.3/fpm/conf.d/99-stream-project.ini
upload_max_filesize = 5G
post_max_size = 5200M
max_input_time = 3600
max_execution_time = 3600
memory_limit = 256M

file_uploads = On
session.cookie_httponly = On
session.cookie_samesite = Lax
expose_php = Off
